plugins {
    id 'java-library'
}

group = 'com.michelet'
version = '0.1.0'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    api 'com.github.Miche-Let:common-auth-core:0.1.1'

    implementation 'org.springframework.boot:spring-boot-autoconfigure:3.5.14'
    implementation 'org.springframework.boot:spring-boot-starter-aop:3.5.14'
    implementation 'org.springframework:spring-webmvc:6.2.8'

    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'

    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    testImplementation 'org.springframework.boot:spring-boot-starter-test:3.5.14'
}

tasks.named('test') {
    useJUnitPlatform()
}